
export const GETTING_ALL_AUTHORS = 'GETTING_ALL_AUTHORS';
export const GET_ALL_AUTHORS_SUCCESS = 'GET_ALL_AUTHORS_SUCCESS';
export const GET_ALL_AUTHORS_FAIL = 'GET_ALL_AUTHORS_FAIL';

export const GETTING_AUTHOR_BY_ID = 'GETTING_AUTHOR_BY_ID';
export const GET_AUTHOR_BY_ID_SUCCESS = 'GET_AUTHOR_BY_ID_SUCCESS';
export const GET_AUTHOR_BY_ID_FAIL = 'GET_AUTHOR_BY_ID_FAIL';

export const GETTING_AUTHORS_BY_NAME = 'GETTING_AUTHORS_BY_NAME';
export const GET_AUTHORS_BY_NAME_SUCCESS = 'GET_AUTHORS_BY_NAME_SUCCESS';
export const GET_AUTHORS_BY_NAME_FAIL = 'GET_AUTHORS_BY_NAME_FAIL';

export const CREATING_AUTHORS = 'CREATING_AUTHORS';
export const CREATE_AUTHORS_SUCCESS = 'CREATE_AUTHORS_SUCCESS';
export const CREATE_AUTHORS_FAIL = 'CREATE_AUTHORS_FAIL';

export const UPDATING_AUTHOR= 'UPDATING_AUTHORS';
export const UPDATE_AUTHOR_SUCCESS= 'UPDATE_AUTHORS_SUCCESS';
export const UPDATE_AUTHOR_FAIL= 'UPDATE_AUTHORS_FAIL';

export const GETTING_AUTHORS_COUNT = 'GETTING_AUTHORS_COUNT';
export const GET_AUTHORS_COUNT_SUCCESS = 'GET_AUTHORS_COUNT_SUCCESS';
export const GET_AUTHORS_COUNT_FAIL = 'GET_AUTHORS_COUNT_FAIL';

export const DELETING_AUTHOR = 'DELETING_AUTHOR';
export const DELETE_AUTHOR_SUCCESS = 'DELETE_AUTHOR_SUCCESS'; 
export const DELETE_AUTHOR_FAIL = 'DELETE_AUTHOR_FAIL'; 