
export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGINING = "LOGINING";
export const LOADING_CURRENT_USER= "LOADING_CURRENT_USER";
export const LOADING_CURRENT_USER_SUCCESS = "LOADING_CURRENT_USER_SUCCESS";
export const LOADING_CURRENT_USER_FAIL = "LOADING_CURRENT_USER_FAIL";
export const LOG_OUT = "LOG_OUT";

// khi xay dung api thi sua sau
export const API_BASE_URL = 'https://localhost:8443/';

//export const API_BASE_URL = '/api';
export const ACCESS_TOKEN = 'accessToken';

// hang so lien quan toi viec xu ly form thi lam tuong tu nhu the nay.Nhưng tạo file trong folder đó
export const NAME_MIN_LENGTH = 4;
export const NAME_MAX_LENGTH = 40;

export const USERNAME_MIN_LENGTH = 3;
export const USERNAME_MAX_LENGTH = 15;

export const EMAIL_MAX_LENGTH = 40;

export const PASSWORD_MIN_LENGTH = 6;
export const PASSWORD_MAX_LENGTH = 20;

//begin singer constants
export const GETTING_SINGERS = 'GETTING_SINGERS';
export const GET_SINGERS_SUCCESS = 'GET_SINGERS_SUCCESS';
export const GET_SINGERS_FAIL = 'GET_SINGERS_FAIL';
export const GETTING_SINGER_BY_ID  = 'GETTING_SINGER_BY_ID';
export const GET_SINGER_BY_ID_SUCCESS  = 'GET_SINGER_BY_ID_SUCCESS';
export const GET_SINGER_BY_ID_FAIL  = 'GET_SINGER_BY_ID_FAIL';
export const CREATING_SINGER = 'CREATING_SINGER';
export const CREATE_SINGER_SUCCESS = 'CREATE_SINGER_SUCCESS';
export const CREATE_SINGER_FAIL = 'CREATE_SINGER_FAIL';
export const DELETING_SINGER = 'DELETING_SINGER';
export const DELETE_SINGER_SUCCESS = 'DELETE_SINGER_SUCCESS';
export const DELETE_SINGER_FAIL = 'DELETE_SINGER_FAIL';
export const UPDATING_SINGER= 'UPDATING_SINGER';
export const UPDATE_SINGER_SUCCESS= 'UPDATE_SINGER_SUCCESS';
export const UPDATE_SINGER_FAIL= 'UPDATE_SINGER_FAIL';
//end singer constants

//begin song constants
export const GETTING_COMMENTS = 'GETTING_COMMENTS';
export const GET_COMMENTS_SUCCESS = 'GETTING_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';
export const GETTING_COMMENTS_BY_SONG_ID = "GETTING_COMMENTS_BY_SONG_ID";
export const GET_COMMENTS_BY_SONG_ID_SUCCESS = "GET_COMMENTS_BY_SONG_ID_SUCCESS";
export const GET_COMMENTS_BY_SONG_ID_FAIL = "GET_COMMENTS_BY_SONG_ID_FAIL";
export const GETTING_COMMENTS_BY_USER_ID = "GETTING_COMMENTS_BY_USER_ID";
export const GETTING_COMMENT_BY_ID = "GETTING_COMMENT_BY_ID";
export const GET_COMMENT_BY_ID_FAIL = "GET_COMMENT_BY_ID_FAIL";
export const CREATING_COMMENT = "CREATING_COMMENT";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"; 
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL"; 
export const UPDATING_COMMENT = "UPDATING_COMMENT";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS"; 
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL"; 
export const DELETING_COMMENT = "DELETING_COMMENT";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"; 
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL"; 
export const UPLOADING_SONG = "UPLOADING_SONG";
export const UPLOAD_SONG_SUCCESS = "UPLOAD_SONG_SUCCESS"
export const UPLOAD_SONG_FAIL = "UPLOAD_SONG_FAIL"
//end song constants

//begin users constants
export const GETTING_USERS = 'GETTING_USERS';
export const GET_USERS_SUCCESS = 'GETTING_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GETTING_USERS_BY_SONG_ID = "GETTING_USERS_BY_SONG_ID";
export const GET_USERS_BY_SONG_ID_SUCCESS = "GET_USERS_BY_SONG_ID_SUCCESS";
export const GET_USERS_BY_SONG_ID_FAIL = "GET_USERS_BY_SONG_ID_FAIL";
export const GETTING_USERS_BY_USER_ID = "GETTING_USERS_BY_USER_ID";
export const GET_USERS_BY_USER_ID_SUCCESS = "GET_USERS_BY_USER_ID_SUCCESS";
export const GET_USERS_BY_USER_ID_FAIL= "GET_USERS_BY_USER_ID_FAIL";
export const GETTING_USER_BY_ID = "GETTING_USER_BY_ID";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS"; 
export const GET_USER_BY_ID_FAIL = "GET_USER_BY_ID_FAIL";
export const CREATING_USER = "CREATING_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"; 
export const CREATE_USER_FAIL = "CREATE_USER_FAIL"; 
export const UPDATING_USER = "UPDATING_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"; 
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"; 
export const DELETING_USER = "DELETING_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"; 
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"; 
export const TOGGLE_USER_EMAIL = "TOGGLE_USER_EMAIL";
//end users constants

//begin playlist constants
export const GETTING_PLAYLISTS = 'GETTING_PLAYLISTS';
export const GET_PLAYLISTS_SUCCESS = 'GETTING_PLAYLISTS_SUCCESS';
export const GET_PLAYLISTS_FAIL = 'GET_PLAYLISTS_FAIL';
export const GETTING_PLAYLISTS_BY_SONG_ID = "GETTING_PLAYLISTS_BY_SONG_ID";
export const GET_PLAYLISTS_BY_SONG_ID_SUCCESS = "GET_PLAYLISTS_BY_SONG_ID_SUCCESS";
export const GET_PLAYLISTS_BY_SONG_ID_FAIL = "GET_PLAYLISTS_BY_SONG_ID_FAIL";
export const GETTING_PLAYLISTS_BY_USER_ID = "GETTING_PLAYLISTS_BY_USER_ID";
export const GET_PLAYLISTS_BY_USER_ID_SUCCESS = "GET_PLAYLISTS_BY_USER_ID_SUCCESS";
export const GET_PLAYLISTS_BY_USER_ID_FAIL= "GET_PLAYLISTS_BY_USER_ID_FAIL";
export const GETTING_PLAYLIST_BY_ID = "GETTING_PLAYLIST_BY_ID";
export const GET_PLAYLIST_BY_ID_SUCCESS = "GET_PLAYLIST_BY_ID_SUCCESS"; 
export const GET_PLAYLIST_BY_ID_FAIL = "GET_PLAYLIST_BY_ID_FAIL";
export const CREATING_PLAYLIST = "CREATING_PLAYLIST";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS"; 
export const CREATE_PLAYLIST_FAIL = "CREATE_PLAYLIST_FAIL"; 
export const UPDATING_PLAYLIST = "UPDATING_PLAYLIST";
export const UPDATE_PLAYLIST_SUCCESS = "UPDATE_PLAYLIST_SUCCESS"; 
export const UPDATE_PLAYLIST_FAIL = "UPDATE_PLAYLIST_FAIL"; 
export const DELETING_PLAYLIST = "DELETING_PLAYLIST";
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS"; 
export const DELETE_PLAYLIST_FAIL = "DELETE_PLAYLIST_FAIL"; 
//end playlist constants

//begin author constants
export const GETTING_AUTHORS = "GETTING_AUTHORS";
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
export const GET_AUTHORS_FAIL = "GET_AUTHORS_FAIL";
//end author constants

//begin song constants
export const GETTING_SONGS = "GETTING_SONGS";
export const GET_SONGS_SUCCESS = "GET_SONGS_SUCCESS";
export const GET_SONGS_FAIL = "GET_SONGS_FAIL";
export const DELETING_SONG = 'DELETING_SONG';
export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS';
export const DELETE_SONG_FAIL = 'DELETE_SONG_FAIL';
export const UPDATING_SONG = "UPDATING_SONG";
export const UPDATE_SONG_SUCCESS = "UPDATE_SONG_SUCCESS"; 
export const UPDATE_SONG_FAIL = "UPDATE_SONG_FAIL"; 
//end song constants
//begin album constants
export const GETTING_ALBUMS = 'GETTING_ALBUMS';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAIL = 'GET_ALBUMS_FAIL';
export const GETTING_ALBUM_BY_ID  = 'GETTING_ALBUM_BY_ID';
export const GET_ALBUM_BY_ID_SUCCESS  = 'GET_ALBUM_BY_ID_SUCCESS';
export const GET_ALBUM_BY_ID_FAIL  = 'GET_ALBUM_BY_ID_FAIL';
export const CREATING_ALBUM = 'CREATING_ALBUM';
export const CREATE_ALBUM_SUCCESS = 'CREATE_ALBUM_SUCCESS';
export const CREATE_ALBUM_FAIL = 'CREATE_ALBUM_FAIL';
export const DELETING_ALBUM = 'DELETING_ALBUM';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';
export const DELETE_ALBUM_FAIL = 'DELETE_ALBUM_FAIL';
export const UPDATING_ALBUM= 'UPDATING_ALBUM';
export const UPDATE_ALBUM_SUCCESS= 'UPDATE_ALBUM_SUCCESS';
export const UPDATE_ALBUM_FAIL= 'UPDATE_ALBUM_FAIL';
//end singer constants