
//begin SCORETYPE constants
export const GETTING_ALL_SCORETYPE = 'GETTING_ALL_SCORETYPE';
export const GET_SCORETYPE_SUCCESS = 'GET_ALL_SCORETYPE_SUCCESS';
export const GET_SCORETYPE_FAIL = 'GET_ALL_SCORETYPE_FAIL';

export const GETTING_SCORETYPE_BY_ID  = 'GETTING_SCORETYPE_BY_ID';
export const GET_SCORETYPE_BY_ID_SUCCESS  = 'GET_SCORETYPE_BY_ID_SUCCESS';
export const GET_SCORETYPE_BY_ID_FAIL  = 'GET_SCORETYPE_BY_ID_FAIL';

export const CREATING_SCORETYPE = 'CREATING_SCORETYPE';
export const CREATE_SCORETYPE_SUCCESS = 'CREATE_SCORETYPE_SUCCESS';
export const CREATE_SCORETYPE_FAIL = 'CREATE_SCORETYPE_FAIL';

export const DELETING_SCORETYPE = 'DELETING_SCORETYPE';
export const DELETE_SCORETYPE_SUCCESS = 'DELETE_SCORETYPE_SUCCESS';
export const DELETE_SCORETYPE_FAIL = 'DELETE_SCORETYPE_FAIL';

export const UPDATING_SCORETYPE= 'UPDATING_SCORETYPE';
export const UPDATE_SCORETYPE_SUCCESS= 'UPDATE_SCORETYPE_SUCCESS';
export const UPDATE_SCORETYPE_FAIL= 'UPDATE_SCORETYPE_FAIL';
//end SCORETYPE constants
//begining Mdal ScoreType
export const SCORETYPE_SHOW_MODAL="SCORETYPE_SHOW_MODAL";
export const SCORETYPE_CLOSE_MODAL="SCORETYPE_CLOSE_MODAL";
