export const ALBUM_SHOW_MODAL="ALBUM_SHOW_MODAL";
export const ALBUM_CLOSE_MODAL="ALBUM_CLOSE_MODAL";
export const OPENING_ALBUM_MODAL="OPENING_ALBUM_MODAL";
export const CLOSING_ALBUM_MODAL="CLOSING_ALBUM_MODAL";