//begin SONG constants

export const GETTING_ALL_SONGS = 'GETTING_ALL_SONGS';
export const GET_ALL_SONGS_SUCCESS = 'GET_ALL_SONGS_SUCCESS';
export const GET_ALL_SONGS_FAIL = 'GET_ALL_SONGS_FAIL';

export const GETTING_SONG_BY_ID  = 'GETTING_SONG_BY_ID';
export const GET_SONG_BY_ID_SUCCESS  = 'GET_SONG_BY_ID_SUCCESS';
export const GET_SONG_BY_ID_FAIL  = 'GET_SONG_BY_ID_FAIL';

export const GETTING_SONGS_BY_SINGER_ID  = 'GETTING_SONGS_BY_SINGER_ID';
export const GET_SONGS_BY_SINGER_ID_SUCCESS  = 'GET_SONGS_BY_SINGER_ID_SUCCESS';
export const GET_SONGS_BY_SINGER_ID_FAIL  = 'GET_SONGS_BY_SINGER_ID_FAIL';

export const GETTING_SONGS_BY_AUTHOR_ID  = 'GETTING_SONGS_BY_AUTHOR_ID';
export const GET_SONGS_BY_AUTHOR_ID_SUCCESS  = 'GET_SONGS_BY_AUTHOR_ID_SUCCESS';
export const GET_SONGS_BY_AUTHOR_ID_FAIL  = 'GET_SONGS_BY_AUTHOR_ID_FAIL';

export const GETTING_SONGS_BY_CATEGORY_ID  = 'GETTING_SONGS_BY_CATEGORY_ID';
export const GET_SONGS_BY_CATEGORY_ID_SUCCESS  = 'GET_SONGS_BY_CATEGORY_ID_SUCCESS';
export const GET_SONGS_BY_CATEGORY_ID_FAIL  = 'GET_SONGS_BY_CATEGORY_ID_FAIL';

export const GETTING_SONGS_BY_NAME  = 'GETTING_SONGS_BY_NAME';
export const GET_SONGS_BY_NAME_SUCCESS  = 'GET_SONGS_BY_NAME_SUCCESS';
export const GET_SONGS_BY_NAME_FAIL  = 'GET_SONGS_BY_NAME_FAIL';

export const CREATING_SONGS = 'CREATING_SONGS';
export const CREATE_SONGS_SUCCESS = 'CREATE_SONGS_SUCCESS';
export const CREATE_SONGS_FAIL = 'CREATE_SONGS_FAIL';

export const UPDATING_SONG= 'UPDATING_SONG';
export const UPDATE_SONG_SUCCESS= 'UPDATE_SONG_SUCCESS';
export const UPDATE_SONG_FAIL= 'UPDATE_SONG_FAIL';

export const DELETING_SONG = 'DELETING_SONG';
export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS';
export const DELETE_SONG_FAIL = 'DELETE_SONG_FAIL';