//begin player constants
export const CHANGE_PLAYER_STATUS = 'CHANGE_PLAYER_STATUS'
export const CHANGE_AUDIO_SRC = 'CHANGE_AUDIO_SRC'
export const PLAYER_PLAYING = 'PLAYER_PLAYING';
export const PLAYER_PAUSE = 'PLAYER_PAUSE';
export const PLAYER_LOADED = 'PLAYER_LOADED';
export const PLAYER_BUFFERING = 'PLAYER_BUFFERING';
export const ADD_SONG_TO_QUEUE = 'ADD_SONG_TO_QUEUE';
export const ADD_MULTI_SONG_TO_QUEUE = 'ADD_MULTI_SONG_TO_QUEUE';
export const TOGGLE_REPEAT = 'TOGGLE_REPEAT';
export const REMOVE_ITEM_FROM_QUEUE = 'REMOVE_ITEM_FROM_QUEUE';
//end player constants
//begin authentication reducers
export const API_BASE_URL = 'https://localhost:8443';
export const ACCESS_TOKEN = 'accessToken';
export const OAUTH2_REDIRECT_URI = 'https://localhost:3000/oauth2-redirect'
export const GOOGLE_AUTH_URL = API_BASE_URL + '/oauth2/authorize/google?redirect_uri=' + OAUTH2_REDIRECT_URI;
export const FACEBOOK_AUTH_URL = API_BASE_URL + '/oauth2/authorize/facebook?redirect_uri=' + OAUTH2_REDIRECT_URI;
export const GITHUB_AUTH_URL = API_BASE_URL + '/oauth2/authorize/github?redirect_uri=' + OAUTH2_REDIRECT_URI;
export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGINING = "LOGINING";
export const LOADING_CURRENT_USER = "LOADING_CURRENT_USER";
export const LOADING_CURRENT_USER_SUCCESS = "LOADING_CURRENT_USER_SUCCESS";
export const LOADING_CURRENT_USER_FAIL = "LOADING_CURRENT_USER_FAIL";
export const LOG_OUT = "LOG_OUT";
export const UPLOADING_AVA = "UPLOADING_AVA";
export const UPLOAD_AVA_SUCCESS = "UPLOAD_AVA_SUCCESS";
export const UPLOAD_AVA_FAIL = "UPLOAD_AVA_FAIL";
export const SIGNING_UP = "SIGNING_UP";
export const SIGN_UP_SUCCESS = "SIGIN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

//Song constants
export const GETTING_ALL_SONG_PAGING = 'GETTING_ALL_SONG_PAGING';
export const GET_ALL_SONG_PAGING_SUCCESS = 'GET_ALL_SONG_PAGING_SUCCESS';
export const GET_ALL_SONG_PAGING_FAIL = 'GET_ALL_SONG_PAGING_FAIL';
export const GETTING_SONG_BY_SINGER_PAGING = 'GETTING_SONG_BY_SINGER_PAGING';
export const GET_SONG_BY_SINGER_PAGING_SUCCESS = 'GET_SONG_BY_SINGER_PAGING_SUCCESS';
export const GET_SONG_BY_SINGER_PAGING_FAIL = 'GET_SONG_BY_SINGER_PAGING_FAIL';
export const GETTING_TOP_5_LIKE = 'GETTING_TOP_5_LIKE';
export const GET_TOP_5_LIKE_SUCCESS = 'GET_TOP_5_LIKE_SUCCESS';
export const GET_TOP_5_LIKE_FAIL = 'GET_TOP_5_LIKE_FAIL';
export const GETTING_TRENDING_SONGS = 'GETTING_TRENDING_SONGS';
export const GET_TRENDING_SONGS_SUCCCESS = 'GET_TRENDING_SONGS_SUCCCESS';
export const GET_TRENDING_SONGS_FAIL = 'GET_TRENDING_SONGS_FAIL';
export const WIPE_FETCH_ON_SCROLL_SONGS = "WIPE_FETCH_ON_SCROLL_SONGS";
export const GETTING_RANDOM_4_JAZZ = 'GETTING_RANDOM_4_JAZZ';
export const GET_RANDOM_4_JAZZ_SUCCESS = 'GET_RANDOM_4_JAZZ_SUCCESS';
export const GET_RANDOM_4_JAZZ_FAIL = 'GET_RANDOM_4_JAZZ_FAIL';
export const GETTING_8_NEWEST = 'GETTING_8_NEWEST';
export const GET_8_NEWEST_SUCCESS = 'GET_8_NEWEST_SUCCESS';
export const GET_8_NEWEST_FAIL = 'GET_8_NEWEST_FAIL';
export const GETTING_RANDOM_4_POP = 'GETTING_RANDOM_4_POP';
export const GET_RANDOM_4_POP_SUCCESS = 'GET_RANDOM_4_POP_SUCCESS';
export const GET_RANDOM_4_POP_FAIL = 'GET_RANDOM_4_POP_FAIL';
export const GETTING_DISCOVER_HEADER_DATA = 'GETTING_DISCOVER_HEADER_DATA';
export const GET_DISCOVER_HEADER_DATA_SUCCESS = 'GET_DISCOVER_HEADER_DATA_SUCCESS';
export const GET_DISCOVER_HEADER_DATA_FAIL = 'GET_DISCOVER_HEADER_DATA_FAIL';
export const GETTING_TOP_POPULAR_BY_SINGER = 'GETTING_TOP_POPULAR_BY_SINGER';
export const GET_TOP_POPULAR_BY_SINGER_SUCCESS = 'GET_TOP_POPULAR_BY_SINGER_SUCCESS';
export const GET_TOP_POPULAR_BY_SINGER_FAIL = 'GET_TOP_POPULAR_BY_SINGER_FAIL';
export const GETTING_SONG_BY_ID = 'GETTING_SONG_BY_ID';
export const GET_SONG_BY_ID_SUCCESS = 'GET_SONG_BY_ID_SUCCESS';
export const GET_SONG_BY_ID_FAIL = 'GET_SONG_BY_ID_FAIL';
export const GETTING_SONG_BY_USER_ID = 'GETTING_SONG_BY_USER_ID';
export const GET_SONG_BY_USER_ID_SUCCESS = 'GET_SONG_BY_USER_ID_SUCCESS';
export const GET_SONG_BY_USER_ID_FAIL = 'GET_SONG_BY_USER_ID_FAIL';
export const LIKING_SONG = 'LIKING_SONG';
export const LIKE_SONG_SUCCESS = 'LIKE_SONG_SUCCESS';
export const LIKE_SONG_FAIL = 'LIKE_SONG_FAIL';
export const GETTING_SONGS_BY_ALBUMS_ID = 'GETTING_SONGS_BY_ALBUMS_ID';
export const GET_SONGS_BY_ALBUMS_ID_SUCCESS = 'GET_SONGS_BY_ALBUMS_ID_SUCCESS';
export const GET_SONGS_BY_ALBUMS_ID_FAIL = 'GET_SONGS_BY_ALBUMS_ID_FAIL';

export const GETTING_SONGS_BY_PLAYLIST_ID = 'GETTING_SONGS_BY_PLAYLIST_ID';
export const GET_SONGS_BY_PLAYLIST_ID_SUCCESS = 'GET_SONGS_BY_PLAYLIST_ID_SUCCESS';
export const GET_SONGS_BY_PLAYLIST_ID_FAIL = 'GET_SONGS_BY_PLAYLIST_ID_FAIL';

export const UPLOADING_SONG = "UPLOADING_SONG";
export const UPLOAD_SONG_SUCCESS = "UPLOAD_SONG_SUCCESS"
export const UPLOAD_SONG_FAIL = "UPLOAD_SONG_FAIL"
export const SAVING_FAV_CAT = 'SAVING_FAV_CAT';
export const SAVE_FAV_CAT_SUCCESS = 'SAVE_FAV_CAT_SUCCESS';
export const SAVE_FAV_CAT_FAIL = 'SAVE_FAV_CAT_FAIL';
export const GETTING_RECOMMENDED_SONGS = 'GETTING_RECOMMENDED_SONGS';
export const GET_RECOMMENDED_SONGS_SUCCESS = 'GET_RECOMMENDED_SONGS_SUCCESS';
export const GET_RECOMMENDED_SONGS_FAIL = 'GET_RECOMMENDED_SONGS_FAIL';

export const GETTING_SONGS_BY_CATEGORY_PAGING = 'GETTING_SONGS_BY_CATEGORY_PAGING';
export const GET_SONGS_BY_CATEGORY_PAGING_SUCCESS = 'GET_SONGS_BY_CATEGORY_PAGING_SUCCESS';
export const GET_SONGS_BY_CATEGORY_PAGING_FAIL = 'GET_SONGS_BY_CATEGORY_PAGING_FAIL';

export const LIKE_PLAYING_SONG_SUCCESS = 'LIKE_PLAYING_SONG_SUCCESS' 

//Song constants

//singer const
export const GETTING_ALL_SINGERS_PAGING = 'GETTING_ALL_SINGERS_PAGING';
export const GET_ALL_SINGERS_PAGING_SUCCESS = 'GET_ALL_SINGERS_PAGING_SUCCESS';
export const GET_ALL_SINGERS_PAGING_FAIL = 'GET_ALL_SINGERS_PAGING_FAIL';
export const WIPE_FETCH_ON_SCROLL_SINGERS = "WIPE_FETCH_ON_SCROLL_SINGERS";
export const GETTING_SINGER_BY_ID = 'GETTING_SINGER_BY_ID';
export const GET_SINGER_BY_ID_SUCCESS = 'GET_SINGER_BY_ID_SUCCESS';
export const GET_SINGER_BY_ID_FAIL = 'GET_SINGER_BY_ID_FAIL';
//singer const

//search const
export const SEARCHING_SONGS_AND_SINGERS = 'SEARCHING_SONGS_AND_SINGERS';
export const SEARCH_SONGS_AND_SINGERS_SUCCESS = 'SEARCH_SONGS_AND_SINGERS_SUCCESS';
export const SEARCH_SONGS_AND_SINGERS_FAIL = 'SEARCH_SONGS_AND_SINGERS_FAIL';
//search const

//comment const
export const GETTING_COMMENTS_BY_PRODUCT_ID = "GETTING_COMMENTS_BY_PRODUCT_ID";
export const GET_COMMENTS_BY_PRODUCT_ID_SUCCESS = "GET_COMMENTS_BY_PRODUCT_ID_SUCCESS";
export const GET_COMMENTS_BY_PRODUCT_ID_FAIL = "GET_COMMENTS_BY_PRODUCT_ID_FAIL";
export const GETTING_COMMENTS_BY_USER_ID = "GETTING_COMMENTS_BY_USER_ID";
export const GET_COMMENTS_BY_USER_ID_SUCCESS = "GET_COMMENTS_BY_USER_ID_SUCCESS";
export const GET_COMMENTS_BY_USER_ID_FAIL = "GET_COMMENTS_BY_USER_ID_FAIL";
export const POSTING_COMMENT = 'POSTING_COMMENT';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL';
export const RECIEVE_REVIEW = 'RECIEVE_REVIEW';
export const POSTING_REPLY = "POSTING_REPLY";
export const POST_REPLY_SUCCESS = "POST_REPLY_SUCCESS";
export const POST_REPLY_FAIL = "POST_REPLY_FAIL";
export const EDITTING_COMMENT = "EDITTING_COMMENT";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_FAIL = "EDIT_COMMENT_FAIL";
//comment const

//album const
export const GETTING_ALBUMS_BY_SINGER_ID = 'GETTING_ALBUMS_BY_SINGER_ID';
export const GET_ALBUMS_BY_SINGER_ID_SUCCESS = 'GET_ALBUMS_BY_SINGER_ID_SUCCESS';
export const GET_ALBUMS_BY_SINGER_ID_FAIL = 'GET_ALBUMS_BY_SINGER_ID_FAIL';
export const GETTING_ALBUMS_BY_ID = 'GETTING_ALBUMS_BY_ID';
export const GET_ALBUMS_BY_ID_SUCCESS = 'GET_ALBUMS_BY_ID_SUCCESS';
export const GET_ALBUMS_BY_ID_FAIL = 'GET_ALBUMS_BY_ID_FAIL';
export const PLAY_ALBUM = 'PLAY_ALBUM';
//album const

//playlist const
export const GETTING_PLAYLISTS_BY_USER_ID = 'GETTING_PLAYLISTS_BY_USER_ID'
export const GET_PLAYLISTS_BY_USER_ID_SUCCESS = 'GET_PLAYLISTS_BY_USER_ID_SUCCESS'
export const GET_PLAYLISTS_BY_USER_ID_FAIL = 'GET_PLAYLISTS_BY_USER_ID_FAIL'
export const GETTING_PLAYLISTS_BY_ID = 'GETTING_PLAYLISTS_BY_ID'
export const GET_PLAYLISTS_BY_ID_SUCCESS = 'GET_PLAYLISTS_BY_ID_SUCCESS'
export const GET_PLAYLISTS_BY_ID_FAIL = 'GET_PLAYLISTS_BY_ID_FAIL';
export const CREATING_PLAYLIST = 'CREATING_PLAYLIST';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_FAIL = 'CREATE_PLAYLIST_FAIL';
export const EDITING_PLAYLIST = 'EDITING_PLAYLIST';
export const EDIT_PLAYLIST_SUCCESS = 'EDIT_PLAYLIST_SUCCESS';
export const EDIT_PLAYLIST_FAIL = 'EDIT_PLAYLIST_FAIL';
export const DELETING_PLAYLIST = 'DELETING_PLAYLIST';
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS';
export const DELETE_PLAYLIST_FAIL = 'DELETE_PLAYLIST_FAIL';
export const ADDING_SONGS_TO_PLAYLIST = 'ADDING_SONGS_TO_PLAYLIST';
export const ADD_SONGS_TO_PLAYLIST_SUCCESS = 'ADD_SONGS_TO_PLAYLIST_SUCCESS';
export const ADD_SONGS_TO_PLAYLIST_FAIL = 'ADD_SONGS_TO_PLAYLIST_FAIL';
export const REMOVING_SONGS_FROM_PLAYLIST = 'REMOVING_SONGS_FROM_PLAYLIST';
export const REMOVE_SONGS_FROM_PLAYLIST_SUCCESS = 'REMOVE_SONGS_FROM_PLAYLIST_SUCCESS';
export const REMOVE_SONGS_FROM_PLAYLIST_FAIL = 'REMOVE_SONGS_FROM_PLAYLIST_FAIL';
//playlist const

//like song of user
export const GETTING_LIKE_SONG_BY_USER_ID="GETTING_LIKE_SONG_BY_USER_ID";
export const GET_LIKE_SONG_BY_USER_ID_SUCCESS="GET_LIKE_SONG_BY_USER_ID_SUCCESS";
export const GET_LIKE_SONG_BY_USER_ID_FAIL="GET_LIKE_SONG_BY_USER_ID_FAIL";
//like song of user
export const WIPE_FETCH_ON_SCROLL_LIKE_SONGS="WIPE_FETCH_ON_SCROLL_LIKE_SONGS";
